/**
 * Theme System Migration Contract
 *
 * Defines the transformation from Nuxt UI theme system to shadcn-vue theming
 */

// ============================================================================
// BEFORE: Nuxt UI Theme System
// ============================================================================

/**
 * Nuxt UI Theme Configuration (nuxt.config.ts)
 *
 * Uses @nuxt/ui module with ui config object:
 */

interface NuxtUIThemeConfig {
  ui: {
    primary?: string // Default: 'green'
    gray?: string // Default: 'slate'
    colors?: string[] // Available colors

    // Custom tokens defined in tokens.css
  }
}

/**
 * Example Nuxt UI config:
 *
 * export default defineNuxtConfig({
 *   modules: ['@nuxt/ui'],
 *   ui: {
 *     primary: 'green',
 *     gray: 'slate',
 *   },
 * })
 *
 * Custom tokens in app/assets/css/tokens.css:
 * :root {
 *   --color-primary-50: ...;
 *   --color-primary-500: ...;
 * }
 */

// ============================================================================
// AFTER: shadcn-vue Theme System
// ============================================================================

/**
 * shadcn-vue Theme Configuration
 *
 * Uses CSS variables with oklch color space
 */

interface ShadcnThemeConfig {
  // components.json - Generated by CLI
  style: 'default' | 'new-york'
  tailwind: {
    config: string // Path to tailwind.config
    css: string // Path to global CSS
    baseColor: string // Base color (slate, gray, zinc, etc.)
    cssVariables: boolean
  }
  iconLibrary: string // Icon library (radix-icons, lucide, etc.)
}

/**
 * Theme CSS Variables (app/assets/css/main.css)
 *
 * Uses oklch color space for better perceptual uniformity
 */

interface ShadcnCSSVariables {
  // Light mode
  '--background': string // Page background
  '--foreground': string // Main text color
  '--card': string // Card background
  '--card-foreground': string // Card text color
  '--popover': string // Popover background
  '--popover-foreground': string
  '--primary': string // Primary brand color
  '--primary-foreground': string
  '--secondary': string // Secondary background
  '--secondary-foreground': string
  '--muted': string // Muted background
  '--muted-foreground': string
  '--accent': string // Accent background
  '--accent-foreground': string
  '--destructive': string // Error/danger color
  '--destructive-foreground': string
  '--border': string // Border color
  '--input': string // Input border color
  '--ring': string // Focus ring color
  '--radius': string // Border radius

  // Dark mode (same variables, different values)
  // Applied via .dark class on <html>
}

// ============================================================================
// MIGRATION PATTERNS
// ============================================================================

/**
 * Pattern 1: Remove Nuxt UI module from nuxt.config.ts
 *
 * BEFORE (nuxt.config.ts):
 * export default defineNuxtConfig({
 *   modules: ['@nuxt/ui', '@nuxt/content', '@nuxtjs/i18n'],
 *   ui: {
 *     primary: 'green',
 *     gray: 'slate',
 *   },
 * })
 *
 * AFTER (nuxt.config.ts):
 * export default defineNuxtConfig({
 *   modules: ['@nuxt/content', '@nuxtjs/i18n', '@nuxtjs/color-mode'],
 *   colorMode: {
 *     classSuffix: '',  // Use .dark instead of .dark-mode
 *   },
 * })
 *
 * NOTE: Keep @nuxtjs/color-mode for theme switching
 */

/**
 * Pattern 2: Initialize shadcn-vue with CLI
 *
 * TERMINAL:
 * $ npx shadcn-vue@latest init
 *
 * CLI prompts:
 * - Style: default (or new-york)
 * - Base color: slate (matches Nuxt UI gray)
 * - CSS variables: Yes
 * - Icon library: radix-icons
 * - Tailwind config location: ./tailwind.config.ts
 * - CSS file location: ./app/assets/css/main.css
 * - Components location: ./app/components/ui
 * - Composables location: ./app/composables
 * - Utils location: ./app/utils
 *
 * This generates components.json with configuration
 */

/**
 * Pattern 3: Update Tailwind config to use CSS variables
 *
 * BEFORE (tailwind.config.ts):
 * export default {
 *   theme: {
 *     extend: {
 *       colors: {
 *         primary: {
 *           50: 'var(--color-primary-50)',
 *           500: 'var(--color-primary-500)',
 *         },
 *       },
 *     },
 *   },
 * }
 *
 * AFTER (tailwind.config.ts - generated by shadcn-vue):
 * export default {
 *   theme: {
 *     container: {
 *       center: true,
 *       padding: '2rem',
 *       screens: {
 *         '2xl': '1400px',
 *       },
 *     },
 *     extend: {
 *       colors: {
 *         border: 'hsl(var(--border))',
 *         input: 'hsl(var(--input))',
 *         ring: 'hsl(var(--ring))',
 *         background: 'hsl(var(--background))',
 *         foreground: 'hsl(var(--foreground))',
 *         primary: {
 *           DEFAULT: 'hsl(var(--primary))',
 *           foreground: 'hsl(var(--primary-foreground))',
 *         },
 *         secondary: {
 *           DEFAULT: 'hsl(var(--secondary))',
 *           foreground: 'hsl(var(--secondary-foreground))',
 *         },
 *         destructive: {
 *           DEFAULT: 'hsl(var(--destructive))',
 *           foreground: 'hsl(var(--destructive-foreground))',
 *         },
 *         muted: {
 *           DEFAULT: 'hsl(var(--muted))',
 *           foreground: 'hsl(var(--muted-foreground))',
 *         },
 *         accent: {
 *           DEFAULT: 'hsl(var(--accent))',
 *           foreground: 'hsl(var(--accent-foreground))',
 *         },
 *         popover: {
 *           DEFAULT: 'hsl(var(--popover))',
 *           foreground: 'hsl(var(--popover-foreground))',
 *         },
 *         card: {
 *           DEFAULT: 'hsl(var(--card))',
 *           foreground: 'hsl(var(--card-foreground))',
 *         },
 *       },
 *       borderRadius: {
 *         lg: 'var(--radius)',
 *         md: 'calc(var(--radius) - 2px)',
 *         sm: 'calc(var(--radius) - 4px)',
 *       },
 *     },
 *   },
 * }
 *
 * NOTE: shadcn-vue CLI generates this automatically
 */

/**
 * Pattern 4: Define CSS variables in main.css
 *
 * BEFORE (app/assets/css/main.css):
 * @import './tokens.css';
 * @tailwind base;
 * @tailwind components;
 * @tailwind utilities;
 *
 * AFTER (app/assets/css/main.css):
 * @tailwind base;
 * @tailwind components;
 * @tailwind utilities;
 *
 * @layer base {
 *   :root {
 *     --background: 0 0% 100%;
 *     --foreground: 222.2 84% 4.9%;
 *     --card: 0 0% 100%;
 *     --card-foreground: 222.2 84% 4.9%;
 *     --popover: 0 0% 100%;
 *     --popover-foreground: 222.2 84% 4.9%;
 *     --primary: 222.2 47.4% 11.2%;
 *     --primary-foreground: 210 40% 98%;
 *     --secondary: 210 40% 96.1%;
 *     --secondary-foreground: 222.2 47.4% 11.2%;
 *     --muted: 210 40% 96.1%;
 *     --muted-foreground: 215.4 16.3% 46.9%;
 *     --accent: 210 40% 96.1%;
 *     --accent-foreground: 222.2 47.4% 11.2%;
 *     --destructive: 0 84.2% 60.2%;
 *     --destructive-foreground: 210 40% 98%;
 *     --border: 214.3 31.8% 91.4%;
 *     --input: 214.3 31.8% 91.4%;
 *     --ring: 222.2 84% 4.9%;
 *     --radius: 0.5rem;
 *   }
 *
 *   .dark {
 *     --background: 222.2 84% 4.9%;
 *     --foreground: 210 40% 98%;
 *     --card: 222.2 84% 4.9%;
 *     --card-foreground: 210 40% 98%;
 *     --popover: 222.2 84% 4.9%;
 *     --popover-foreground: 210 40% 98%;
 *     --primary: 210 40% 98%;
 *     --primary-foreground: 222.2 47.4% 11.2%;
 *     --secondary: 217.2 32.6% 17.5%;
 *     --secondary-foreground: 210 40% 98%;
 *     --muted: 217.2 32.6% 17.5%;
 *     --muted-foreground: 215 20.2% 65.1%;
 *     --accent: 217.2 32.6% 17.5%;
 *     --accent-foreground: 210 40% 98%;
 *     --destructive: 0 62.8% 30.6%;
 *     --destructive-foreground: 210 40% 98%;
 *     --border: 217.2 32.6% 17.5%;
 *     --input: 217.2 32.6% 17.5%;
 *     --ring: 212.7 26.8% 83.9%;
 *   }
 * }
 *
 * NOTE: Values are in HSL format (hue saturation lightness)
 * NOTE: shadcn-vue CLI generates these automatically
 * NOTE: tokens.css is no longer needed
 */

/**
 * Pattern 5: Theme toggle component (AppHeader.vue)
 *
 * BEFORE (AppHeader.vue - Nuxt UI):
 * <script setup lang="ts">
 * const colorMode = useColorMode()
 * const isDark = computed(() => colorMode.value === 'dark')
 *
 * function toggleTheme() {
 *   colorMode.preference = isDark.value ? 'light' : 'dark'
 * }
 * </script>
 *
 * <template>
 *   <UButton
 *     :icon="isDark ? 'i-heroicons-sun' : 'i-heroicons-moon'"
 *     variant="ghost"
 *     @click="toggleTheme"
 *   />
 * </template>
 *
 * AFTER (AppHeader.vue - shadcn-vue):
 * <script setup lang="ts">
 * const colorMode = useColorMode()
 * const isDark = computed(() => colorMode.value === 'dark')
 *
 * function setTheme(theme: 'light' | 'dark' | 'system') {
 *   colorMode.preference = theme
 * }
 * </script>
 *
 * <template>
 *   <DropdownMenu>
 *     <DropdownMenuTrigger as-child>
 *       <Button variant="ghost" size="icon">
 *         <Icon
 *           :icon="isDark ? 'radix-icons:sun' : 'radix-icons:moon'"
 *           class="h-5 w-5"
 *         />
 *       </Button>
 *     </DropdownMenuTrigger>
 *     <DropdownMenuContent align="end">
 *       <DropdownMenuItem @click="setTheme('light')">
 *         <Icon icon="radix-icons:sun" class="me-2 h-4 w-4" />
 *         Light
 *       </DropdownMenuItem>
 *       <DropdownMenuItem @click="setTheme('dark')">
 *         <Icon icon="radix-icons:moon" class="me-2 h-4 w-4" />
 *         Dark
 *       </DropdownMenuItem>
 *       <DropdownMenuItem @click="setTheme('system')">
 *         <Icon icon="radix-icons:desktop" class="me-2 h-4 w-4" />
 *         System
 *       </DropdownMenuItem>
 *     </DropdownMenuContent>
 *   </DropdownMenu>
 * </template>
 *
 * NOTE: More comprehensive theme options (light/dark/system)
 */

/**
 * Pattern 6: Update color class names throughout codebase
 *
 * BEFORE (Nuxt UI color classes):
 * - text-gray-500 → text-muted-foreground
 * - text-gray-900 dark:text-gray-100 → text-foreground
 * - bg-gray-50 dark:bg-gray-800 → bg-muted
 * - bg-white dark:bg-gray-900 → bg-card
 * - border-gray-200 dark:border-gray-700 → border-border
 * - text-primary-500 → text-primary
 * - bg-primary-500 → bg-primary
 *
 * AFTER (shadcn-vue semantic classes):
 * - text-muted-foreground (automatically dark mode aware)
 * - text-foreground
 * - bg-muted
 * - bg-card
 * - border-border
 * - text-primary
 * - bg-primary
 *
 * NOTE: Semantic color names eliminate need for dark: variants
 */

/**
 * Pattern 7: Remove tokens.css file
 *
 * BEFORE:
 * app/assets/css/
 *   ├── main.css
 *   └── tokens.css  ← Custom color tokens
 *
 * AFTER:
 * app/assets/css/
 *   └── main.css    ← All theme variables here
 *
 * NOTE: All theme configuration moves to main.css @layer base
 */

/**
 * Pattern 8: Update package.json dependencies
 *
 * BEFORE:
 * {
 *   "dependencies": {
 *     "@nuxt/ui": "^4.3.0",
 *     "nuxt": "^4.0.0"
 *   }
 * }
 *
 * AFTER:
 * {
 *   "dependencies": {
 *     "nuxt": "^4.0.0",
 *     "@nuxtjs/color-mode": "^3.5.2",
 *     "@iconify/vue": "^4.1.1",
 *     "@iconify-json/radix-icons": "^1.2.0",
 *     "class-variance-authority": "^0.7.0",
 *     "clsx": "^2.1.0",
 *     "tailwind-merge": "^2.2.0",
 *     "radix-vue": "^1.9.0"
 *   },
 *   "devDependencies": {
 *     "shadcn-nuxt": "^0.10.0"
 *   }
 * }
 *
 * NOTE: shadcn-vue components depend on radix-vue primitives
 */

// ============================================================================
// MIGRATION CHECKLIST
// ============================================================================

/**
 * Theme migration steps:
 *
 * 1. [ ] Run `npx shadcn-vue@latest init` to generate config
 * 2. [ ] Remove @nuxt/ui from nuxt.config.ts modules
 * 3. [ ] Remove ui config object from nuxt.config.ts
 * 4. [ ] Keep @nuxtjs/color-mode module (configure classSuffix: '')
 * 5. [ ] Delete app/assets/css/tokens.css
 * 6. [ ] Update app/assets/css/main.css with shadcn-vue variables
 * 7. [ ] Update tailwind.config.ts with generated config
 * 8. [ ] Update theme toggle component to use DropdownMenu
 * 9. [ ] Replace hardcoded colors with semantic variables:
 *        - text-gray-500 → text-muted-foreground
 *        - bg-gray-50 → bg-muted
 *        - border-gray-200 → border-border
 * 10. [ ] Update package.json (remove @nuxt/ui, add shadcn deps)
 * 11. [ ] Test light mode appearance
 * 12. [ ] Test dark mode appearance
 * 13. [ ] Test theme switching (light/dark/system)
 * 14. [ ] Verify all components respect theme
 * 15. [ ] Check localStorage persistence (via @nuxtjs/color-mode)
 */

// ============================================================================
// COMMON PITFALLS
// ============================================================================

/**
 * PITFALL 1: Forgetting to remove @nuxt/ui module
 *
 * ❌ WRONG (nuxt.config.ts):
 * modules: ['@nuxt/ui', 'shadcn-nuxt']
 *
 * ✅ CORRECT (nuxt.config.ts):
 * modules: ['@nuxt/content', '@nuxtjs/color-mode', '@nuxtjs/i18n']
 *
 * Why: @nuxt/ui and shadcn-vue conflict; only use one UI library
 */

/**
 * PITFALL 2: Using dark: variants with semantic colors
 *
 * ❌ WRONG:
 * <div class="text-muted-foreground dark:text-gray-300">
 *   Text
 * </div>
 *
 * ✅ CORRECT:
 * <div class="text-muted-foreground">
 *   Text
 * </div>
 *
 * Why: Semantic colors automatically adapt to dark mode
 */

/**
 * PITFALL 3: Not configuring @nuxtjs/color-mode classSuffix
 *
 * ❌ WRONG (nuxt.config.ts):
 * colorMode: {
 *   // Uses .dark-mode by default
 * }
 *
 * ✅ CORRECT (nuxt.config.ts):
 * colorMode: {
 *   classSuffix: '',  // Use .dark instead of .dark-mode
 * }
 *
 * Why: shadcn-vue expects .dark class, not .dark-mode
 */

/**
 * PITFALL 4: Mixing HSL and oklch color spaces
 *
 * ❌ WRONG (main.css):
 * :root {
 *   --primary: oklch(0.5 0.2 200);
 *   --secondary: 210 40% 96.1%;  ← HSL format
 * }
 *
 * ✅ CORRECT (main.css):
 * :root {
 *   --primary: 222.2 47.4% 11.2%;  ← All HSL
 *   --secondary: 210 40% 96.1%;
 * }
 *
 * Why: Stick to one color space (HSL) for consistency
 * NOTE: shadcn-vue default uses HSL, not oklch
 */

/**
 * PITFALL 5: Not testing system theme preference
 *
 * Test system theme with:
 * 1. Select "System" theme option
 * 2. Change OS theme (macOS: System Preferences → Appearance)
 * 3. Verify app updates automatically
 *
 * Why: System theme should respect OS preference
 */

export type {NuxtUIThemeConfig, ShadcnCSSVariables, ShadcnThemeConfig}
